name: Build & Deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare folder
        run: mkdir -p build

      - run: npm ci
        working-directory: build
      
      - name: Build
        run: npm run build
        working-directory: build

      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-deployment-artifact
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
