name: Build & Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        working-directory: build
      
      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
