name: Build & Deploy

on: [pull_request, push]

concurrency:
  group: build-and-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Upload as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist


  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - run: echo test
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
