name: Build

on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare folder
        run: mkdir -p build

      - run: npm ci
      
      - name: Build
        run: npm run build
